"""A person's edit to the screenplay, written byte for byte (ADR 0016).

ADR 0006 still holds: software never rewrites authored text on its own. This
is the one path by which a *person's* edit to a screenplay file reaches disk.
The text they wrote is written as they wrote it -- nothing is parsed and
reserialized -- after checking that the file is still the one they opened.
"""

from __future__ import annotations

import hashlib
import os
from collections import Counter
from pathlib import Path
from typing import Any

from .errors import CineToasterError, ResourceNotFoundError, ValidationError
from .events import Event, append_event

#: Findings an edit to the screenplay can create or clear (SPEC-0006).
SCRIPT_CODES = ("script_scene_missing", "script_anchor_missing", "script_anchor_ambiguous",
                "dialogue_uncovered", "line_drift", "line_unscripted")
BOM = "﻿"
MAX_SCREENPLAY_BYTES = 5 * 1024 * 1024


class ScreenplayConflictError(CineToasterError):
    """The file changed after the editor opened it."""

    code = "revision_conflict"
    http_status = 409


class ScreenplayReadOnlyError(CineToasterError):
    code = "read_only"
    http_status = 409


def digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _editable(root: Path, production: dict[str, Any]) -> tuple[bool, str]:
    if production.get("script_generated_by"):
        return False, (f"This screenplay is generated by {production['script_generated_by']}; "
                       f"edit its source and generate it again.")
    if not os.access(root, os.W_OK):
        return False, "The production directory is read only."
    return True, ""


def screenplay_files(root: Path, production: dict[str, Any]) -> dict[str, Any]:
    """What the editor opens: each file's text and the revision it was read at."""

    editable, reason = _editable(root, production)
    files = []
    for name in production.get("script_files") or []:
        raw = (root / name).read_bytes()
        text = raw.decode("utf-8")
        files.append({
            "path": name,
            "text": text.removeprefix(BOM),
            "revision": digest(raw),
            "line_endings": "crlf" if "\r\n" in text else "lf",
        })
    return {"files": files, "editable": editable, "reason": reason,
            "problem": production.get("script_problem") or ""}


def _script_findings(production: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {**finding, "scene_id": scene["id"]}
        for scene in production["scenes"]
        for finding in scene["findings"]
        if finding["code"] in SCRIPT_CODES
    ]


def _key(finding: dict[str, Any]) -> tuple:
    return (finding["code"], finding["scene_id"], tuple(finding.get("shots") or []), finding["message"])


def edit_screenplay(
    root: Path,
    path: str,
    text: str,
    revision: str,
    *,
    actor: str = "unknown",
    rationale: str = "",
) -> dict[str, Any]:
    """Write one screenplay file as the person wrote it, if it is still the file they opened."""

    from .project import load_production

    root = Path(root).expanduser().resolve()
    before = load_production(root)
    if path not in (before.get("script_files") or []):
        raise ValidationError(f"{path!r} is not one of this production's screenplay files",
                              files=before.get("script_files") or [])
    editable, reason = _editable(root, before)
    if not editable:
        raise ScreenplayReadOnlyError(reason)
    if not isinstance(text, str):
        raise ValidationError("text must be a string")

    target = root / path
    if not target.is_file():
        raise ResourceNotFoundError(f"{path} is gone")
    current = target.read_bytes()
    if digest(current) != revision:
        raise ScreenplayConflictError(
            f"{path} changed since it was opened. Reload it; nothing was written.",
            expected_revision=revision, actual_revision=digest(current),
        )

    # The person's text, with the two file conventions an editor drops restored.
    original = current.decode("utf-8")
    body = text.removeprefix(BOM)
    if "\r\n" in original:
        body = body.replace("\r\n", "\n").replace("\n", "\r\n")
    if original.startswith(BOM):
        body = BOM + body
    raw = body.encode("utf-8")
    if len(raw) > MAX_SCREENPLAY_BYTES:
        raise ValidationError("The screenplay file is too large")
    if raw == current:
        return {"path": path, "revision": revision, "changed": False, "impact": {"new": [], "cleared": [], "counts": {}}}

    temporary = target.with_name(f".{target.name}.saving")
    with open(temporary, "wb") as handle:
        handle.write(raw)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, target)

    after = load_production(root)
    old = {_key(f): f for f in _script_findings(before)}
    new = {_key(f): f for f in _script_findings(after)}
    impact = {
        "new": [new[key] for key in new.keys() - old.keys()][:50],
        "cleared": [old[key] for key in old.keys() - new.keys()][:50],
        "counts": dict(Counter(f["code"] for f in new.values())),
    }
    revision_after = digest(raw)
    append_event(root, Event.create(
        "screenplay.edited", before["id"], path=path, actor=actor, rationale=rationale[:500],
        revision_before=revision, revision_after=revision_after,
        new_findings=len(impact["new"]), cleared_findings=len(impact["cleared"]),
    ))
    return {"path": path, "revision": revision_after, "changed": True, "impact": impact}
