"""Where a production keeps its versions, and the index a person reads (ADR 0021).

A version lives with what it is a version of:

    scenes/<scene>/versions/v12.mp4          the cut
    scenes/<scene>/versions/v12.scene.yaml   the breakdown that made it
    scenes/<scene>/versions/VERSIONS.md      every version: date, length, what changed, verdict, note
    sequences/<sequence>/versions/...        the same for a sequence

`VERSIONS.md` is regenerated from the records whenever a version is
recorded or judged -- SINGULAR's own table, kept by hand there, kept by the
runtime here. It is derived: editing it changes nothing; the records are
the truth.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

INDEX = "VERSIONS.md"


def scene_versions(scene_file: str) -> str:
    """The project-relative folder of a scene's versions, beside its breakdown."""

    return (Path(scene_file).parent / "versions").as_posix()


def sequence_versions(sequence_id: str) -> str:
    return f"sequences/{sequence_id}/versions"


VERDICT = {"approved": "✅ approved", "rejected": "✗ rejected", "pending": "pending", "superseded": "superseded"}


def _row(version: dict[str, Any], folder: Path, root: Path) -> str:
    media = version.get("media") or ""
    link = f"[{version['id']}]({_relative(root / media, folder)})" if media else version["id"]
    seconds = f"{round(float(version.get('duration_seconds') or 0))} s" if version.get("duration_seconds") else ""
    when = str(version.get("created_at") or "")[:16].replace("T", " ")
    summary = " ".join(str(version.get("summary") or "").split()).replace("|", "/")
    note = " ".join(str(version.get("note") or "").split()).replace("|", "/")
    renditions = ", ".join(f"[{key}]({_relative(root / value, folder)})"
                           for key, value in (version.get("renditions") or {}).items())
    if renditions:
        summary += f" (also as {renditions})"
    return f"| {link} | {when} | {seconds} | {summary} | {VERDICT.get(version.get('verdict') or 'pending', version.get('verdict'))} | {note} |"


def _relative(target: Path, folder: Path) -> str:
    import os

    return Path(os.path.relpath(target, folder)).as_posix()


def write_index(root: Path, folder: Path, title: str, versions: list[dict[str, Any]], latest_note: str = "") -> Path:
    """`VERSIONS.md` in `folder`, newest first."""

    folder.mkdir(parents=True, exist_ok=True)
    ordered = sorted(versions, key=lambda item: str(item.get("created_at") or ""), reverse=True)
    approved = next((item for item in ordered if item.get("verdict") == "approved"), None)
    lines = [
        f"# {title} -- versions", "",
        "Generated by Cine Toaster from the production's records whenever a version is made or judged; "
        "editing this file changes nothing. Cite a version by its id (\"in v3, shot 11...\").", "",
    ]
    if approved:
        lines += [f"Approved: **{approved['id']}**.", ""]
    if latest_note:
        lines += [latest_note, ""]
    lines += ["| version | made | length | what it is | verdict | note |", "|---|---|---|---|---|---|"]
    lines += [_row(item, folder, root) for item in ordered]
    path = folder / INDEX
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def index_scene(root: Path, scene_id: str) -> Path | None:
    """Regenerate a scene's `VERSIONS.md` from its state."""

    from .project import load_scene

    scene = load_scene(root, scene_id)
    if scene is None:
        return None
    folder = root / scene_versions(scene["file"])
    return write_index(root, folder, f"{scene_id} {scene.get('title') or ''}".strip(), scene.get("assemblies") or [])


def index_sequence(root: Path, sequence_id: str) -> Path | None:
    from .project import load_production

    sequence = next((item for item in load_production(root)["sequences"] if item["id"] == sequence_id), None)
    if sequence is None:
        return None
    folder = root / sequence_versions(sequence_id)
    return write_index(root, folder, sequence.get("label") or sequence_id, sequence.get("versions") or [])
